name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Download Hugo
        run: |
          HUGO_VERSION="0.126.0"
          wget https://github.com/goharbor/harbor/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
          tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/
          rm hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public